# Generated by Django 3.2.6 on 2021-09-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snock',
            old_name='symfoni',
            new_name='ticker',
        ),
    ]
